apiVersion: rbac.authorization.k8s.io/v1
# 此角色绑定允许 "jane" 读取 "default" 名字空间中的 Pods
kind: RoleBinding
metadata:
  name: nga-test1-rolebinding
  namespace: nga
subjects:
# 你可以指定不止一个“subject（主体）”
- kind: ServiceAccount
  name: nga-test1 # "name" 是区分大小写的
  namespace: nga
roleRef:
  # "roleRef" 指定与某 Role 或 ClusterRole 的绑定关系
  kind: Role # 此字段必须是 Role 或 ClusterRole
  name: nga-test1-role     # 此字段必须与你要绑定的 Role 或 ClusterRole 的名称匹配
  apiGroup: rbac.authorization.k8s.io